// export const FIREBASE_CONFIG = {
//     apiKey: "AIzaSyBUSGdsoHuZlNXIQkpPOUWGPoZblbPUusU",
//     authDomain: "pvmnt2.firebaseapp.com",
//     databaseURL: "https://pvmnt2.firebaseio.com",
//     projectId: "pvmnt2",
//     storageBucket: "pvmnt2.appspot.com",
//     messagingSenderId: "25455448021"
// };

export const FIREBASE_CONFIG = {
    apiKey: "AIzaSyBunuxZwS4Q--yTxiyNz3c7TWmEJgEvBSQ",
    authDomain: "dynamicmapping-e3fe5.firebaseapp.com",
    databaseURL: "https://dynamicmapping-e3fe5.firebaseio.com",
    projectId: "dynamicmapping-e3fe5",
    storageBucket: "dynamicmapping-e3fe5.appspot.com",
    messagingSenderId: "668335161540"
};